baseurl = "https://chris-prener.github.io/vacancy/"
languageCode = "en-us"
title = "Urban Prairies: Vacant Land in St. Louis"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

# Ignore files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Christopher Prener, Ph.D."
	description = "Research on the Pervasiveness of Vacant Land and Buildings in St. Louis"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []



	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = ""
		
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Urban Prairies: \rVacant Land in St. Louis"
		
		# The icons will be shown if you enter your username
		twitter = ""
		github = "chris-prener"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		
		# homepage url
		home="https://chris-prener.github.io/"
		
		copyright = [
			"&copy; 2017-2018 [CC-BY-SA 4.0](/barriers/license)",
			"Design: [HTML5 UP](//html5up.net)",
		]

  [params.avatar]
    hide = true
    
  [params.rss]
    hide = true

	[params.about]
		hide  = false
		title = "Research on the Pervasiveness of Vacant Land and Buildings in St. Louis, Missouri"
		content = "The City of St. Louis (which is an independent city separate from St. Louis County) has a [well documented](http://www.stltoday.com/news/local/metro/amid-drumbeat-from-falling-bricks-st-louis-to-ramp-up/article_1e237c9c-95e7-5c01-8d0c-92a2fe1a5c78.html) pattern of extensive vacancy. What is not well known, however, is the actual number of vacancies in the city. A variety of estimates have been made in the last several decades. Most recently, the Mayor's office release an estimate of at least 24,000 vacant properties as part of the City's [Preliminary Resilience Assessment](https://www.stlouis-mo.gov/government/departments/mayor/initiatives/resilience/documents/upload/PRA1001_Report_Inside_10.pdf). Our *Urban Prairies* project aims to produce estimates of vacancy at the parcel level in St. Louis. [As of January 2017](/vacancy17), we believe that there are between 32,431 (25%) and 48,013 (37%) vacant parcels out of a total of 128,644. We are particularly interested in how vacant land clusters spatially to produce areas in St. Louis that appear to 'return to nature'."


		[params.portfolio]
		hide  = false
		title = "publications and data"

    		# The images and thumbnails are stored under static/images
    		[[params.portfolio.gallery]]
    			image = "fulls/01.jpg"
    			thumb = "thumbs/01_thumb.jpg"
    			title = "Forthcoming *Journal of Urban Affairs* Article"
    			description = "Initial analysis of prarie land, available on [SocArXiv](https://dx.doi.org/10.17605/OSF.IO/BC7EH) without restriction and from [*JUA*](https://www.tandfonline.com/doi/abs/10.1080/07352166.2018.1474079?journalCode=ujua20) for readers with an institutional affiliation"

    		[[params.portfolio.gallery]]
    			image = "fulls/02.jpg"
    			thumb = "thumbs/02_thumb.jpg"
    			title = "2017 Vacant Parcel Data"
    			description = "Data used in our initial publication, available on [GitHub](https://github.com/chris-prener/vacancy-data), [licensed for re-use](https://github.com/chris-prener/vacancy-data/blob/master/LICENSE), and citeable with [Zenodo](https://doi.org/10.5281/zenodo.1241429)"

	[params.recentposts]
		hide  = true
		title = "recent articles"

	[params.contact]
		hide  = true
		email = "chris.prener@slu.edu"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "background"
	url  = "/background"
	weight = 20

[[menu.main]]
	name = "2017 approach"
	url  = "/approach17"
	weight = 21

[[menu.main]]
	name = "2017 analysis"
	url  = "/vacancy17"
	weight = 22

[[menu.main]]
	name = "faq"
	url  = "/faq"
	weight = 40
	
[[menu.main]]
	name = "research team"
	url  = "/team"
	weight = 44
	